{
 "title": "Brain Tumor MLOps — PFA 2024/2025 Nadia Zemani",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Prédictions",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "sum(predictions_total)" }
   ]
  },
  {
   "title": "Confiance Moyenne (%)",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "prediction_confidence_last * 100"
    }
   ]
  },
  {
   "title": "Latence Moyenne (ms)",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(prediction_latency_seconds_sum[5m]) / rate(prediction_latency_seconds_count[5m]) * 1000"
    }
   ]
  },
  {
   "title": "Erreurs",
   "type": "stat",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "sum(prediction_errors_total)" }
   ]
  },
  {
   "title": "Prédictions par classe (temps réel)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "targets": [
    { "expr": "predictions_total", "legendFormat": "{{predicted_class}}" }
   ]
  },
  {
   "title": "Latence des prédictions (ms)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 4, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(prediction_latency_seconds_sum[1m]) / rate(prediction_latency_seconds_count[1m]) * 1000",
     "legendFormat": "Latence ms"
    }
   ]
  }
 ]
}